import "../styles/globals.css";
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import React from "react";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import { WixClientContextProvider } from "@/context/WixClientContext";
import { CartContextProvider } from "@/context/CartContext";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <WixClientContextProvider>
      <CartContextProvider>
        <html lang="en">
          <body
            className={`${quicksand.className} flex flex-col`}
            suppressHydrationWarning={true}
          >
            <div
              className="bg-white text-gray-900 transition-colors duration-200 ease-in-out
        min-h-screen flex items-center justify-center align-middle"
            >
              <NavBar />

              <div className="w-full h-full max-w-screen-xl">
                <div>{children}</div>
              </div>
            </div>
            <Footer />
          </body>
        </html>
      </CartContextProvider>
    </WixClientContextProvider>
  );
}
